import ResumeFile from "../Assets/Resume-Mangal.pdf";
export const ResumeJSONData = [
  {
    name: "Aakesh",
    email: "aakesh@gmail.com",
    mobile: 9879561233,
    gender: "Male",
    skills: ["JAVA, JAVASCRIPT, ASP.NET, RUBY"],
    experience: "4 Years",
    resume: { ResumeFile },
  },
  {
    name: "Pranali more",
    email: "pranali@gmail.com",
    mobile: 9846774276,
    gender: "Female",
    skills: ["C++, PYTHON,REACT, SQL"],
    experience: "7 Years",
    resume: { ResumeFile },
  },
  {
    name: "Aarav",
    email: "aarav@gmail.com",
    mobile: 9878564243,
    gender: "Male",
    skills: ["ANGULAR, JAVASCRIPT, Sql, CSS"],
    experience: "5 Years",
    resume: { ResumeFile },
  },
  {
    name: "Khushi kapoor",
    email: "khushi@gmail.com",
    mobile: 9846212142,
    gender: "Female",
    skills: ["PHP, REACT, CSS, SQL"],
    experience: "6 Years",
    resume: { ResumeFile },
  },
  {
    name: "Vihaan",
    email: "vihaan@gmail.com",
    mobile: 9816564241,
    gender: "Male",
    skills: ["PYTHON, BOOTSTRAP, JAVASCRIPT, ASP.NET"],
    experience: "3 Years",
    resume: { ResumeFile },
  },
  {
    name: "Ayansh Rana",
    email: "ayansh@gmail.com",
    mobile: 9816004248,
    gender: "Male",
    skills: ["SQL, JAVASCRIPT, HTML, REACT, CSS"],
    experience: "8 Years",
    resume: { ResumeFile },
  },
  {
    name: "Shruti Tambe",
    email: "shruti@gmail.com",
    mobile: 9846554246,
    gender: "Female",
    skills: ["FLUTTER, ANDROID, DART, SQL"],
    experience: "3 Years",
    resume: { ResumeFile },
  },
  {
    name: "Snehal Jadhav",
    email: "snehal@gmail.com",
    mobile: 9846994296,
    gender: "Female",
    skills: ["PHP, C#, REACT, SQL"],
    experience: "2 Years",
    resume: { ResumeFile },
  },
  {
    name: "Mangal Rawat",
    email: "mangal@gmail.com",
    mobile: 7843954696,
    gender: "Male",
    skills: [" C#, REACT, SQL"],
    experience: "1 Years",
    resume: { ResumeFile },
  },
  {
    name: "Akshy Jadhav",
    email: "akshay@gmail.com",
    mobile: 8874958399,
    gender: "Male",
    skills: ["PHP, C#, REACT, SQL"],
    experience: "2 Years",
    resume: { ResumeFile },
  },
  {
    name: "Imam Siddique",
    email: "imam@gmail.com",
    mobile: 7769785955,
    gender: "Male",
    skills: ["PHP, REACT, SQL"],
    experience: "3 Years",
    resume: { ResumeFile },
  },
  {
    name: "Shaurabh Kumar",
    email: "saurabh@gmail.com",
    mobile: 9988676774,
    gender: "Male",
    skills: [" C#, REACT, SQL"],
    experience: "4 Years",
    resume: { ResumeFile },
  },
  {
    name: "Raajnsh Singh",
    email: "rajnish@gmail.com",
    mobile: 7589486744,
    gender: "Male",
    skills: [" ASP.NET, SQL"],
    experience: "1 Years",
    resume: { ResumeFile },
  },

  {
    name: "Rahul Yadav",
    email: "rahul@gmail.com",
    mobile: 8674995735,
    gender: "Male",
    skills: [" C#, ASP.NET, SQL"],
    experience: "2 Years",
    resume: { ResumeFile },
  },
];
